### ISSUE TITLE
Can't add attachment to task comment after updating to 0.16.0

### ISSUE THREAD

**Issue by nekopaldee** [cgwire/kitsu#1030]
**Context**
Can't add an attachment to task comment after updating to 0.16.0

Kitsu version: 0.16.0
Production type: VFX

**Description**
After trying to add an attachment to the comment clicking sent doesn't do anything, except spin around indefinitely.
The log reported 400 (Bad Request) and Uncaught (in promise) TypeError: h.response.body.message.indexOf is not a function
    at TaskInfo.vue:677:1

**Screenshots**
![msedge_A65dzLxVyL](https://user-images.githubusercontent.com/26713157/223056298-582f0f65-4656-47a8-9a80-53b03124829b.gif)

![image](https://user-images.githubusercontent.com/26713157/223056344-dc6a5624-f5ec-4602-9bf8-2b09b4d5b87d.png)

**Desktop:**

 - OS: Windows 11 (22H2 Build 22621.1344)
 - Browser: Edge
 - Version: 110.0.1587.63

But it affects the other browser too.

**Comment by EvanBldy** [comment]
Hi @nekopaldee,
Thanks for the report ! 
It's a problem on Zou side :)
I have fixed the problem and built a new release for Zou : 0.16.3.
Can you try with the last version and close your issue if it's okay for you ? 
Thanks!

**Comment by nekopaldee** [comment]
Hi @EvanBldy,
I upgraded Zou to 0.16.3 and it's now working flawlessly.
Thanks for the fast bug fix!
